version:
    '3.1'
services:
    app:
        container_name: docker-node-mongo
        restart:
            always
        ports:
            - 1900:1900
        build: .
        links:
            - mongo
        networks:
            - app-network
         
    mongo:
        container_name: mongo
        image:
            mongo
        # ports: 
        #     - 27017:27017
        networks:
           - app-network
    
networks:
    app-network:
      driver: bridge

    



